user_key = "0x19e573f3801c7b2e4619998342e8e305e1692184cbacd220c04198a04c36b7d2"
previous_nonce = "0x03"
previous_shares = "0x64"
nullifier = "0x00"
previous_unlocks_at = "0x00"
declared_time_reference = "0x0f4240"
previous_commitment_leaf = "0x2c1b45cba36c96d9049a38f445fba21d58f14de2bfd88b818e0c35cb2dca9e33"
commitment_index = "0x03"
tree_depth = "0x02"
expected_root = "0x176444929ca9e37f64ec3647eac6b28af6c38754f35cbb75249b6f19c3fba4e7"
merkle_proof = ["0x2d9ef1023cef3c2d6c293641045639a3e5b22bbfff248297c2fec63c210aa1c2", "0x1929818f8c0678d133d3785d5d996bb759282170e0c64784cbd6d8252cadb153", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00"]
token_address = "0x7775e4b6f4d40be537b55b6c47e09ada0157bd"
chain_id = "0x01"
amount = "0x32"
arbitrary_calldata_hash = "0x1234567890abcdef"
receiver_address = "0x742d35cc6634c0532925a3b8d4c9db96c4b4d8b6"
relayer_fee_amount = "0x01"
is_tl_swap = false
tl_swap_shares_amounts = ["0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00"]
