chain_id = ""
commitment_index = ""
current_balance = ""
expected_root = ""
merkle_proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
note_stack_commitment_index = ""
note_stack_m = ""
note_stack_merkle_proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
note_stack_r = ""
note_stack_x = ""
note_stack_y = ""
nullifier = ""
previous_commitment = ""
previous_nonce = ""
previous_unlocks_at = ""
relayer_fee_amount = ""
token_address = ""
tree_depth = ""
user_key = ""
