
user_key = "0x19e573f3801c7b2e4619998342e8e305e1692184cbacd220c04198a04c36b7d2"

token_address = "0x7775e4b6f4d40be537b55b6c47e09ada0157bd"

amount = "0x32"

chain_id = "0x01"

previous_nonce = "0x03"

previous_shares = "0x00"

nullifier = "0x00"

previous_unlocks_at = "0x00"

previous_commitment_leaf = "0x09f59efd111368198f55c7ad63e48d65fe4389f089f6f11b472166794765e82d"

commitment_index = "0x03"

tree_depth = "0x02"

expected_root = "0x05b95e559549e14dbe0ae410a0d2382e184ec672a10206a554a44297a4f4010e"

merkle_proof = ["0x2d9ef1023cef3c2d6c293641045639a3e5b22bbfff248297c2fec63c210aa1c2", "0x1929818f8c0678d133d3785d5d996bb759282170e0c64784cbd6d8252cadb153", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00", "0x00"]