amount = ""
chain_id = ""
commitment_index = ""
expected_root = ""
merkle_proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifier = ""
previous_commitment_leaf = ""
previous_nonce = ""
previous_shares = ""
previous_unlocks_at = ""
token_address = ""
tree_depth = ""
user_key = ""
