[workspace]
members = [
    "main/entry",
    "main/deposit",
    "main/withdraw", 
    "lib/poseidon-ctr-encryption",
    "lib/pedersen-commitments",
    "lib/poseidon",
    "lib/lean-imt-verify"
]

compiler_version = "1.0.0-beta.12"

target_dir = "./main"